[package]
name = "zapusk"
version = "0.1.19"
edition = "2024"
license = "MIT"
description = "TUI for managing local web development projects"
keywords = ["tui", "dev-server", "local-development", "process-manager"]
categories = ["command-line-utilities", "development-tools"]
authors = ["Rafael Egli"]
repository = "https://github.com/e9li/zapusk"
homepage = "https://git.e9li.com/e9li/zapusk"

[[bin]]
name = "zapusk"
path = "src/main.rs"

[dependencies]
ratatui = "0.30"
crossterm = { version = "0.29", features = ["event-stream"] }
futures-util = "0.3"
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
toml = "1"
anyhow = "1"
dirs = "6"
chrono = { version = "0.4", features = ["serde"] }
clap = { version = "4", features = ["derive"] }
libc = "0.2"
shell-words = "1"
serde_json = "1"
clap_complete = "4"
