[package]
name = "zapusk"
version = "0.1.6"
edition = "2024"

[[bin]]
name = "zapusk"
path = "src/main.rs"

[dependencies]
ratatui = "0.30"
crossterm = "0.29"
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
toml = "1"
anyhow = "1"
dirs = "6"
chrono = { version = "0.4", features = ["serde"] }
clap = { version = "4", features = ["derive"] }
libc = "0.2"
shell-words = "1"
serde_json = "1"
